import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider } from "react-router";
import { ThemeProvider } from "@/providers";
import { setAuthToken, setOnUnauthorized, onRequestError } from "@/request";
import { router } from "@/router";
import { settings } from "../config/settings.ts";
import { useAuthStore } from "@/store/auth";
import "./i18n";
import "./index.css";
setOnUnauthorized(() => { setAuthToken(null); useAuthStore.getState().clear(); try { localStorage.removeItem("token"); } catch {} const from = window.location.pathname + window.location.search; if (!from.startsWith(settings.path + "/auth")) { void router.navigate(`/auth?redirect=${encodeURIComponent(from)}`, { replace: true }); } });
onRequestError((error, method) => { const meta = method.meta; if (meta && meta.silent) return; if (error.kind === "cancel") return; });
const App = () => { return <StrictMode><ThemeProvider><RouterProvider router={router} /></ThemeProvider></StrictMode>; };
createRoot(document.getElementById("root") as HTMLElement).render(App());
